import { Permission } from '../domain/permission';
import { Role } from '../domain/role';
import { User } from '../domain/user';

/**
 * Seed data for the in-memory adapters (ADR 0002). Volumes are deliberate: fourteen users is more
 * than one page, so paging is exercised by simply opening the screen rather than only in a spec.
 * The tenant is the same mock slug the shell remembers in `shared-kernel/tenant`.
 */
export const SEED_TENANT_ID = 'smart-management';

const CREATED_AT = '2026-01-15T09:00:00.000Z';
const UPDATED_AT = '2026-07-30T14:22:00.000Z';

function base(id: string) {
  return { id, tenantId: SEED_TENANT_ID, createdAt: CREATED_AT, updatedAt: UPDATED_AT };
}

export const SEED_PERMISSIONS: readonly Permission[] = [
  {
    ...base('perm-01'),
    code: 'TENANT_READ',
    name: 'View tenants',
    module: 'Tenant',
    isActive: true,
    description: 'Read tenant records and their settings.',
  },
  {
    ...base('perm-02'),
    code: 'TENANT_WRITE',
    name: 'Manage tenants',
    module: 'Tenant',
    isActive: true,
    description: 'Create, update and suspend tenants.',
  },
  {
    ...base('perm-03'),
    code: 'TENANT_SETTINGS_WRITE',
    name: 'Manage tenant settings',
    module: 'Tenant',
    isActive: true,
  },
  {
    ...base('perm-04'),
    code: 'USER_READ',
    name: 'View users',
    module: 'User',
    isActive: true,
    description: 'Read the user directory.',
  },
  {
    ...base('perm-05'),
    code: 'USER_WRITE',
    name: 'Manage users',
    module: 'User',
    isActive: true,
    description: 'Create, update and deactivate users.',
  },
  { ...base('perm-06'), code: 'USER_DELETE', name: 'Delete users', module: 'User', isActive: true },
  {
    ...base('perm-07'),
    code: 'USER_IMPERSONATE',
    name: 'Impersonate users',
    module: 'User',
    isActive: false,
    description: 'Disabled pending a support policy.',
  },
  { ...base('perm-08'), code: 'ROLE_READ', name: 'View roles', module: 'Role', isActive: true },
  { ...base('perm-09'), code: 'ROLE_WRITE', name: 'Manage roles', module: 'Role', isActive: true },
  { ...base('perm-10'), code: 'ROLE_DELETE', name: 'Delete roles', module: 'Role', isActive: true },
  {
    ...base('perm-11'),
    code: 'PERMISSION_READ',
    name: 'View permissions',
    module: 'Permission',
    isActive: true,
  },
  {
    ...base('perm-12'),
    code: 'PERMISSION_WRITE',
    name: 'Manage permissions',
    module: 'Permission',
    isActive: true,
  },
  { ...base('perm-13'), code: 'GROUP_READ', name: 'View groups', module: 'Group', isActive: true },
  {
    ...base('perm-14'),
    code: 'GROUP_WRITE',
    name: 'Manage groups',
    module: 'Group',
    isActive: true,
  },
  {
    ...base('perm-15'),
    code: 'GROUP_MEMBER_WRITE',
    name: 'Manage group members',
    module: 'Group',
    isActive: true,
  },
];

export const SEED_ROLES: readonly Role[] = [
  {
    ...base('role-01'),
    name: 'Administrator',
    description: 'Full access to every management surface.',
    isActive: true,
    isDefault: false,
    permissionCodes: SEED_PERMISSIONS.filter((p) => p.isActive).map((p) => p.code),
  },
  {
    ...base('role-02'),
    name: 'Tenant manager',
    description: 'Manages tenants and their settings.',
    isActive: true,
    isDefault: false,
    permissionCodes: ['TENANT_READ', 'TENANT_WRITE', 'TENANT_SETTINGS_WRITE', 'USER_READ'],
  },
  {
    ...base('role-03'),
    name: 'User manager',
    description: 'Manages the user directory and role assignments.',
    isActive: true,
    isDefault: false,
    permissionCodes: ['USER_READ', 'USER_WRITE', 'USER_DELETE', 'ROLE_READ'],
  },
  {
    ...base('role-04'),
    name: 'Member',
    description: 'Read-only access. Assigned to every new user by default.',
    isActive: true,
    isDefault: true,
    permissionCodes: ['TENANT_READ', 'USER_READ', 'ROLE_READ', 'PERMISSION_READ', 'GROUP_READ'],
  },
  {
    ...base('role-05'),
    name: 'Auditor',
    description: 'Read-only access retained for compliance reviews.',
    isActive: false,
    isDefault: false,
    permissionCodes: ['TENANT_READ', 'USER_READ', 'ROLE_READ'],
  },
];

export const SEED_USERS: readonly User[] = [
  {
    ...base('user-01'),
    userName: 'ada',
    email: 'ada.lovelace@smart-management.local',
    firstName: 'Ada',
    lastName: 'Lovelace',
    isActive: true,
    emailVerified: true,
    lastLoginAt: '2026-08-07T08:14:00.000Z',
    roleIds: ['role-01'],
  },
  {
    ...base('user-02'),
    userName: 'grace',
    email: 'grace.hopper@smart-management.local',
    firstName: 'Grace',
    lastName: 'Hopper',
    isActive: true,
    emailVerified: true,
    lastLoginAt: '2026-08-06T17:02:00.000Z',
    roleIds: ['role-03'],
  },
  {
    ...base('user-03'),
    userName: 'alan',
    email: 'alan.turing@smart-management.local',
    firstName: 'Alan',
    lastName: 'Turing',
    isActive: true,
    emailVerified: true,
    lastLoginAt: '2026-08-05T11:47:00.000Z',
    roleIds: ['role-02', 'role-04'],
  },
  {
    ...base('user-04'),
    userName: 'katherine',
    email: 'katherine.johnson@smart-management.local',
    firstName: 'Katherine',
    lastName: 'Johnson',
    isActive: true,
    emailVerified: true,
    lastLoginAt: '2026-08-04T09:30:00.000Z',
    roleIds: ['role-04'],
  },
  {
    ...base('user-05'),
    userName: 'margaret',
    email: 'margaret.hamilton@smart-management.local',
    firstName: 'Margaret',
    lastName: 'Hamilton',
    isActive: true,
    emailVerified: true,
    phoneNumber: '+44 20 7946 0011',
    lastLoginAt: '2026-08-01T13:05:00.000Z',
    roleIds: ['role-03'],
  },
  {
    ...base('user-06'),
    userName: 'barbara',
    email: 'barbara.liskov@smart-management.local',
    firstName: 'Barbara',
    lastName: 'Liskov',
    isActive: true,
    emailVerified: false,
    roleIds: ['role-04'],
  },
  {
    ...base('user-07'),
    userName: 'edsger',
    email: 'edsger.dijkstra@smart-management.local',
    firstName: 'Edsger',
    lastName: 'Dijkstra',
    isActive: false,
    emailVerified: true,
    lastLoginAt: '2026-03-12T10:20:00.000Z',
    roleIds: ['role-05'],
  },
  {
    ...base('user-08'),
    userName: 'donald',
    email: 'donald.knuth@smart-management.local',
    firstName: 'Donald',
    lastName: 'Knuth',
    isActive: true,
    emailVerified: true,
    lastLoginAt: '2026-07-28T15:55:00.000Z',
    roleIds: ['role-04'],
  },
  {
    ...base('user-09'),
    userName: 'radia',
    email: 'radia.perlman@smart-management.local',
    firstName: 'Radia',
    lastName: 'Perlman',
    isActive: true,
    emailVerified: true,
    phoneNumber: '+44 20 7946 0093',
    lastLoginAt: '2026-08-07T07:41:00.000Z',
    roleIds: ['role-02'],
  },
  {
    ...base('user-10'),
    userName: 'leslie',
    email: 'leslie.lamport@smart-management.local',
    firstName: 'Leslie',
    lastName: 'Lamport',
    isActive: true,
    emailVerified: false,
    roleIds: ['role-04'],
  },
  {
    ...base('user-11'),
    userName: 'frances',
    email: 'frances.allen@smart-management.local',
    firstName: 'Frances',
    lastName: 'Allen',
    isActive: true,
    emailVerified: true,
    lastLoginAt: '2026-06-19T16:10:00.000Z',
    roleIds: ['role-04'],
  },
  {
    ...base('user-12'),
    userName: 'tony',
    email: 'tony.hoare@smart-management.local',
    firstName: 'Tony',
    lastName: 'Hoare',
    isActive: false,
    emailVerified: true,
    roleIds: ['role-05'],
  },
  {
    ...base('user-13'),
    userName: 'jean',
    email: 'jean.sammet@smart-management.local',
    firstName: 'Jean',
    lastName: 'Sammet',
    isActive: true,
    emailVerified: true,
    lastLoginAt: '2026-07-02T12:00:00.000Z',
    roleIds: ['role-04'],
  },
  {
    ...base('user-14'),
    userName: 'shafi',
    email: 'shafi.goldwasser@smart-management.local',
    firstName: 'Shafi',
    lastName: 'Goldwasser',
    isActive: true,
    emailVerified: true,
    lastLoginAt: '2026-08-06T19:26:00.000Z',
    roleIds: ['role-03', 'role-04'],
  },
];
