import { TaxIdType } from './tax-id-type';
import { BusinessType } from './business-type';
import { CompanySize } from './company-size';

export interface AddCompanyProfile {
  tenantId: string;
  taxIdType: TaxIdType;
  taxId: string;
  secondaryTaxId: string;
  vatNumber: string;
  companyRegistrationNumber: string;
  legalName: string;
  tradeName: string;
  legalNameLocal: string;
  tradeNameLocal: string;
  businessType: BusinessType;
  industry: string;
  companySize: CompanySize;
  address: string;
  city: string;
  stateProvince: string;
  postalCode: string;
  countryCode: string;
  countryName: string;
  phoneCountryCode: string;
  phone: string;
  mobile: string;
  fax: string;
  email: string;
  website: string;
  foundationDate?: string;
  incorporationDate?: string;
  incorporationCountry: string;
  annualRevenue?: number;
  revenueCurrency: string;
  employeeCount?: number;
  bankAccounts: string;
  description: string;
  socialMedia: string;
  contactPersonName: string;
  contactPersonTitle: string;
  contactPersonEmail: string;
  contactPersonPhone: string;
  contactPersonLanguage: string;
  isVerified: boolean;
  verifiedAt?: string;
  verifiedByUserId?: string;
  verificationNotes: string;
  verificationDocuments: string;
  complianceCertifications: string;
}
