export enum TaxIdType {
  None = 'None',
  Cnpj = 'Cnpj',
  Cpf = 'Cpf',
  Ie = 'Ie',
  Im = 'Im',
  Ein = 'Ein',
  Ssn = 'Ssn',
  Vat = 'Vat',
  Eori = 'Eori',
  Utr = 'Utr',
  CompanyNumber = 'CompanyNumber',
  Siret = 'Siret',
  Siren = 'Siren',
  StNr = 'StNr',
  UStIdNr = 'UStIdNr',
  Abn = 'Abn',
  Acn = 'Acn',
  Tfn = 'Tfn',
  Bn = 'Bn',
  Sin = 'Sin',
  Usci = 'Usci',
  Cn = 'Cn',
  Gst = 'Gst',
  Pan = 'Pan',
  Rfc = 'Rfc',
  Other = 'Other'
}