import { UserRole } from './user-role';
import { UserGroup } from './user-group';

export interface User {
  id: string;
  tenantId: string;
  keycloakUserId: string;
  email: string;
  userName: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  fullName?: string;
  fullNameLocal?: string;
  displayName?: string;
  phoneCountryCode?: string;
  phone?: string;
  mobile?: string;
  avatarUrl?: string;
  isAdmin: boolean;
  isActive: boolean;
  isEmailVerified: boolean;
  emailVerifiedAt?: string;
  isPhoneVerified: boolean;
  phoneVerifiedAt?: string;
  preferredLanguage?: string;
  preferredTimezone?: string;
  preferredCurrency?: string;
  preferredDateFormat?: string;
  preferredTimeFormat?: string;
  countryCode?: string;
  city?: string;
  stateProvince?: string;
  twoFactorEnabled: boolean;
  twoFactorMethod?: string;
  lastLoginAt?: string;
  lastLoginIp?: string;
  lastLoginCountry?: string;
  failedLoginAttempts: number;
  lockedUntil?: string;
  passwordChangedAt?: string;
  mustChangePassword: boolean;
  notificationPreferences?: string;
  spokenLanguages?: string;
  workingHours?: string;
  deactivationReason?: string;
  deactivatedAt?: string;
  gdprConsent: boolean;
  gdprConsentDate?: string;
  marketingConsent: boolean;
  dataProcessingConsent: boolean;
  dataRetentionDate?: string;
  createdAt: string;
  updatedAt?: string;
  createdByUserId?: string;
  userRoles?: UserRole[];
  userGroups?: UserGroup[];
}
